name: Deploy to Another Repository gh-pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current repo
      uses: actions/checkout@v4
      with: 
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        fetch-depth: 0
        ref: master

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Get last commit details
      run: |
        echo "GIT_AUTHOR_NAME=${{ github.event.head_commit.author.name }}" >> $GITHUB_ENV
        echo "GIT_AUTHOR_EMAIL=${{ github.event.head_commit.author.email }}" >> $GITHUB_ENV
        echo "GIT_COMMIT_MESSAGE=$(echo '${{ github.event.head_commit.message }}' | base64 -w 0)" >> $GITHUB_ENV

    - name: Prepare gh-pages
      env:
        ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        GIT_AUTHOR_NAME: ${{ env.GIT_AUTHOR_NAME }}
        GIT_AUTHOR_EMAIL: ${{ env.GIT_AUTHOR_EMAIL }}
        REMOTE_REPOSITORY: "Aivle4-Team3/Aplus-EDU"
      run: |
        mkdir _site
        cd _site
        git config --global user.name ${GIT_AUTHOR_NAME}
        git config --global user.email ${GIT_AUTHOR_EMAIL}
        git init
        git remote add origin https://x-access-token:${ACCESS_TOKEN}@github.com/${REMOTE_REPOSITORY}.git
        git fetch origin gh-pages
        git checkout gh-pages

    - name: Build Jekyll site
      run: |
        gem install bundler
        bundle install
        bundle exec jekyll build

    - name: Push to gh-pages
      env:
        GIT_COMMIT_MESSAGE: ${{ env.GIT_COMMIT_MESSAGE }}
      run: |
        cd _site/
        git add .
        git commit -m "$(echo $GIT_COMMIT_MESSAGE | base64 --decode)"
        git push origin gh-pages
